### PR TITLE
[docs] Show older releases on docs.modm.io

### PR DESCRIPTION
**Pull request by rleh**

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Very nice, especially the automatic release detection!

**Review by chris-durand — APPROVED** [review]
Very nice!

**Comment by salkinium** [comment]
@rleh I think you still need to copy the json file from the develop to 2021q4 folder to make it detectable on docs.modm.io.
Not sure how to get the json file for 2021q3, perhaps just copy it too and ignore the issues?

**Comment by rleh** [comment]
Done.

**Comment by salkinium** [comment]
It works! Supergeil!!

**Pull request merged**
