### PR TITLE
[avr] Add AVR Timer support via lbuild module

### PR DESCRIPTION
**Pull request by TomSaw**
As a followup to #163 i quickly setup this fresh branch and cloned the platform/timer/avr/[sources] from @ASMfreaK  https://github.com/ASMfreaK/modm/tree/avr_timers. Hope to not have violated @ASMfreaK © this way.

State according to #163 (not yet verified):

- [x] module implemented
- [x] tc8 implemented
  - [ ] with docs
  - [ ] with examples
- [ ] tc8-async implemented
  - [ ] with docs
  - [ ] with examples
- [ ] tc16 implemented
  - [ ] with docs
  - [ ] with examples
- [ ] tc10 implemented
  - [ ] with docs
  - [ ] with examples

### CODE REVIEW

**Comment by rleh** [comment]
FYI @TomSaw, you could have just taken @ASMfreaK's commit 597a1ee0a8240d3b5feb638be1ec51636881d0fd and cherry-picked it onto your branch:
```bash
git fetch origin 597a1ee0a8240d3b5feb638be1ec51636881d0fd
git cherry-pick 597a1ee0a8240d3b5feb638be1ec51636881d0fd
# Resolv merge conflicts...
git cherry-pick --continue --no-edit
```

**Comment by TomSaw** [comment]
Aha 👆🙄 This could have been my first apply of cherry-picks... got the concept - thanks @rleh for the little briefing.

**Comment by TomSaw** [comment]
For the protocol: **This timer support will take some time.**
I felt the maturity and dug for the STM32 blue pill i had lying around since a while, just to see, how the timers may look and feel.

**And this was mindblowing: such a huge difference 😱 modm + STM32! What happened?**

I'm currently entering a universe of extended possibilities with strong gravitation and now being concerned this PR may suffer the same fate like #163... being left, Timeless.

However, i still want to challenge it for the sport of learning more about lbuild in a silent environment.

**Comment by salkinium** [comment]
Sure, but keep in mind that the STM32 timer API in modm is a little… weird. It works fine to a certain degree, but even things like simply setting a PWM of a certain period is very challenging and also just… different per Timer instance. The API was designed more for motor control, so there's a lot of low level stuff in there that's overwhelming (at least to me).

It's not the best, perhaps it would be good to have a simpler API with some actual use-cases in mind, like PWM, PPM, InputCapture, etc.

**Comment by rleh** [comment]
Please don't take the STM32 timer API as a reference. Redesigning it and rewriting the stm32 timer code is on my todo-list, but not particularly high...

I'm going to open an issue soon with a proposal for a timer API, happy to discuss timer use-cases and hardware-specific limitations over there to have a better API in modm in the future: #594

**Comment by TomSaw** [comment]
I'm in.
So we conceptuate the API in #594 and this PR concentrates on the implementation for AVR, right?

**Pull request closed without merging**
