### PR TITLE
[driver] Fix inconsistencies in TCS34xx

### PR DESCRIPTION
**Pull request by TomSaw**
Call me petty but these two little inconsistencies make me sick.

### CODE REVIEW

**Comment by salkinium** [comment]
Call me petty but "Fixed inconsitencies" is not how it's spelled 🤪

**Comment by TomSaw** [comment]
Holly 😁

**Comment by salkinium** [comment]
I was actually referring to the commit message, didn't even notice in the title myself.
Let's rename it to `[driver] Fix inconsistencies in TCS34xx driver`

**Comment by salkinium** [comment]
I cancelled the CI to not delay the other PRs. We're working on it.

**Pull request merged**
