### PR TITLE
[cmake] First define the compiler before further detection

### PR DESCRIPTION
**Pull request by strongly-typed**
Before the fix:
```
➜  blink git:(develop) ✗ pwd
/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink
➜  blink git:(develop) ✗ lbuild build

➜  blink git:(develop) ✗ cd build
➜  build git:(develop) ✗ cmake ..
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build
➜  build git:(develop) ✗ make VERBOSE=1
/usr/local/Cellar/cmake/3.15.1/bin/cmake -S/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink -B/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.15.1/bin/cmake -E cmake_progress_start /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/blink.dir/build.make CMakeFiles/blink.dir/depend
cd /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build && /usr/local/Cellar/cmake/3.15.1/bin/cmake -E cmake_depends "Unix Makefiles" /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles/blink.dir/DependInfo.cmake --color=
Dependee "/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles/blink.dir/DependInfo.cmake" is newer than depender "/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles/blink.dir/depend.internal".
Dependee "/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build/CMakeFiles/blink.dir/depend.internal".
Scanning dependencies of target blink
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/blink.dir/build.make CMakeFiles/blink.dir/build
[  3%] Building CXX object CMakeFiles/blink.dir/modm/src/modm/architecture/driver/atomic/flag.cpp.o
arm-none-eabi-g++   -I/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/modm/ext -I/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/modm/ext/cmsis/core -I/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/modm/ext/cmsis/device -I/Users/usr/Dev/modm/modm-s
[...]
➜  build git:(develop) ✗ arm-none-eabi-g++ --verbose
[...]
gcc version 8.2.1 20181213 (release) [gcc-8-branch revision 267074] (GNU Tools for Arm Embedded Processors 8-2018-q4-major)
```
which does not make sense to report the AppleClang and then using `arm-none-eabi-g++`

After the fix:
```
➜  blink git:(fix/cmake) ✗ pwd
/Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink
➜  blink git:(fix/cmake) ✗ lbuild build
Recomputing device cache...

➜  blink git:(fix/cmake) ✗ cd build
➜  build git:(fix/cmake) ✗ cmake ..
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/local/bin/arm-none-eabi-gcc
-- Check for working C compiler: /usr/local/bin/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/arm-none-eabi-g++
-- Check for working CXX compiler: /usr/local/bin/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/usr/Dev/modm/modm-strongly-ci-macos/examples/stm32f4_discovery/blink/build
➜  build git:(fix/cmake) ✗
```

### CODE REVIEW

**Comment by strongly-typed** [comment]
May fix #263

**Comment by salkinium** [comment]
Can you add this commit to your macOS Travis CI work and check if that works?

**Comment by strongly-typed** [comment]
It seems to, the [unrecognized command line option '-mmacosx-version-min=10.14'](https://api.travis-ci.com/v3/job/221004964/log.txt) is gone.

**Review by salkinium — APPROVED** [review]
Thanks!

**Pull request merged**
