### PR TITLE
[graphic] Rewrite graphics - Round 1

### PR DESCRIPTION
**Pull request by TomSaw**
# Synopsis of added goods
- **Generic colors**
  - Feature complete
    - All operations with **saturation arithmetics**
    - **Conversion** between any instances of **Hsv <-> Rgb** 
  - **Bit granularity** for `modm::Gray`. Same for `modm::Rgb` and `modm::Hsv` cause they're made form 3x `modm::Gray`
    - Symetric scaling. Example convertions 2-bit Gray ---> 4-bit Gray.
        - 0b00 --> 0b0000
        - 0b01 --> 0b0101 // No stupid lshift, the gap is filled up
        - 0b10 --> 0b1010
        - 0b11 --> 0b1111 // Saturated stays saturated, white stays white
  - **C++20 concepts** for colortypes and colorgroups (currently _ColorPlane_ and _ColorPalletizing_). These concepts are very handy to modelate overload resolutions on specialision of buffers and their methods. They're also the key for good readability.
- **Generic graphic buffers**
  - **Arbitrary Color** and **Resolution**
  - Full support for `Buffer` **interoperation**: Copy/Convert buffers from sources (Flash, Ram, _SD-Card not yet implemented_) to destinations (Ram, Display).
  - **Pixel palletizing** for 1-, 2- and 4-bit grayscale (1-bit == Monochrome)
  - **Indexed colors** for compressed, canned Images but also for resource-friendly drawing and texting.
- **Buffer manipulations**
  - **Optimized** drawing of primitives (**Point, Line, Circle, Ellipse**)
  - <s>`foregroundColor`</s>, <s>`backgroundColor`</s> -> replaced by a **colormap***
  - **DMA** whenever possible: each of `clear()` and `Buffer` copies without color-conversion / -mapping
  - Generic **fill patterns** (gradients, checkerboard, stripes). See examples
- **Support external hardware**
  - All features also work efficiently on **external hardware** using **resumable functions**: Currently implemented for ili9341
  - ili9341::`draw(Point / HLine / VLine / Rectangle, Section)` is hyper-fast cause no pixel-pushing is involved. Just some register setup and DMA, filling the area. See #666 . This is great for Prototyping and Tools: You can f.e. draw/update colored Bars with next to zero resource-footprint.

## Roadmap
- [ ] Merge #781
- [ ] Merge #782
- [ ] Refactor graphic directory structure
- [ ] New generic `graphic::Buffer` including Display driver write-methods
- [ ] New `graphic::shape` classes and their rendering into graphic buffers

## TODO
- [x] Pass Buffer<...> in RAM or Flash using accessors
- [x] Support arbitrary non-grayscale Buffers
- [x] Support arbitrary grayscale Color and Buffers
  - [x] `color::GrayT<...>` implementation to cover f.e. 4 and 16 level grayscale displays.
  - [x] `graphic::Buffer<GrayT<...>, ...>` implementation. Targets pixel stacking algorithms.
- [ ] Specialise Buffer<Monochrome, .. > for speed
- [ ] lbuild options
  - [ ] Disable modm_asserts in GrayD<D> constructors
  - [ ] Visualize refresh for Display-drivers ( Similar to Android Developer option )
- [ ] Add/Update tests
  - [ ]  Buffer conversion
- [ ] New examples
  - [ ] Simplest to advanced rendering
  - [ ] Custom `graphic::LocalPainter` with simple UI widgets like Button, Checkbox and Slider
  - [ ] Generic Tetris Game as rich overall demo

Here's a list for **follow up rounds**.
#  Rewrite Graphics - Round 2

- **Support STM32 DMA2D**
  - [](https://www.st.com/resource/en/product_training/STM32L4-System-ChromART(DMA2D).pdf): Compose a new `modm::Buffer` from multiple `modm::Buffer` like layers in graphics manipulation software.
  - Porter & Duff composing. Conversion-constructors for each in `modm::ui::color::*` but also depends on what DMA2D can do. See [uPainter](https://github.com/salkinium/upainter)
- **Canned images on SD-Card**
- **Drawing**
  - Dithering
  - Anti-Aliasing
  - Line-thickness and Line-style (Dotted, Dashed)
  - More shapes

### CODE REVIEW

**Comment by salkinium** [comment]
It's the exams phase so I don't have a detailed review, but here are some rought points:

- Overall: Yes, very nice!
- Don't put an endianess template parameter in the color format, especially if you don't even store the underlying data in said endian format. Instead use [`modm::toBigEndian`/`modm::fromBigEndian`](https://github.com/modm-io/modm/blob/develop/src/modm/math/utils/endianness.hpp) inside the buffer functions.
- I'm unsure about the Resumable interface. I see the issue with the SPI transfers for the off-device frame buffer of the Ili9341, however there's a lot of duplication with RF_CALL stuff, that would fall away when we switch to fibers.
- Not sure why the Buffer needs to know the type of the Painter? I think the buffer should only abstract the resolution/data format/pixel access and the Painter should access that via a virtual interface (which may include optimizations like your fast methods).
- The `.font` files and the `SConscript.generate` can be deleted as they are duplicated in `modm/tools/font_creator/fonts`, however, the `ubuntu_36.font` should be copied there. Perhaps in future we could replace the `modm/tools/font_creator` with something better.

**Comment by TomSaw** [comment]
Thanks @salkinium for the quick review. I'm happy with such short mentoring, Nice to hear the code isn't bullshit and thanks for the feedback.

> ... especially if you don't even store the underlying data in said endian format

<strike>It pays out to handle the Color in delivery format from minute one. The Endian feature in Rgb565 is not yet completely implemented but **I do store it in said format and works as expected**. </strike> Another optimal solution arised - no more need to adjust endianes. See my latest comments in #666.

>    Buffer needs to know the type of the Painter?

<strike>`Painter` manipulates `Buffer / Display` only via one of `drawFast(...)` because the memory-mappings of `monochrome Buffer / colored Buffer / Display` work so differently. I don't wanted a composition-coupling via pointer between `Painter` and `Buffer`. For max. speed, `Painter` needs to be a Base to `Buffer / Display` with virtual `drawFast(...)` methods.</strike>
EDIT: Took me a while to see 🧐 I had to swap the inheritance 🤓:

Before: `Buffer`/`Display`-> `Painter`, Now: **`Painter`->`Buffer` / `Display`**

#### Advantages
- Inline instead of virtual calls of drawFast(..) makes drawing ~1-20% faster
- Template declarations of `Buffer<...>` and it's methods simplified
- `RemotePainter`->`Ili9341` now works with Resumable Functions! Hurray

The declarations of `LocalPainter` / `RemotePainter` are ugly for now. Working on this...

**Comment by TomSaw** [comment]
Wait... You're writing or reading the exams @salkinium ???

**Comment by TomSaw** [comment]
# Initial commited  **very generic Colors**

## Examples for the new color types:
`namespace color {`
`using Rgb888 = RgbT<8> // Each channel as uint8_t`
`using Rgb161616 = RgbT<16> // Each channel as uint16_t`
`using Rgb101010 = RgbT<10> // Also valid, still consumes 3 * uint16_t but affects saturation arithmetics and color convertions`
`using Rgb565 = RgbT<5,6,5, true> // true says: stack R, G and B into the smallest fitting unsigned int.`
`using Gray1 = GrayT<1> // Black and White, the new "monochrome"` 
`using Gray2 = GrayT<2> // 4 shades of gray`
`using Gray4 = GrayT<4> // 16 shades of gray`
<strike>`using Gray4 = GrayT<5.64> // 50 shades of gray`</strike>  Discarded due to no applications
`using Gray8 = GrayT<8> // 64 shades of gray`
`}`

## Trapezoidal conversion*
_*Anybody an idea for a better headline?_

Means, when you convert `color::GrayT<a>` to `color::GrayT<b>` where {a < b} the value is not simple copied but scaled!
`0b11 in Gray2 converts to 0b1111 in Gray4`, White keeps white!
`0b10 in Gray2 converts to 0b1010 in Gray4` a.s.o.
Since `color::RgbT` and `color::HsvT` make their 3 channels from `GreyT` this applies to any color-conversion!

## Applications for arbitrary color-formats
"Invent" your own colors to be used f.e. in this situation:
You want to drop some pixels on a Rgb565 display but only black, white, red and green is required  - could be a logger-output with some syntax highlight.
Declare a `graphic::Buffer<color::Gray2, Resolution> buffer;`. Gray2 can distinct your 4 desired colors.

Along with the call of write(buffer) you provide a **color-mapping** to the display-driver: `{color::html::Black, color::html::White, color::html::Red, color::html::Green}`. Any four colors supported by the display are valid.

### This trick may spare lot's of ressources
- Spare 8 times RAM / Flash cause an uin16_t fits 8 `Grey2`-pixels instead of one `Rgb565`-pixel.
- Copying image-data is way faster. Applies f.e. when writing text.

#### Unfinished business
Need to adjust the algorithms of `graphic::Buffer<color::GreyT<..>, Resolution>` so pixels will be stacked in the Buffer.

**Comment by TomSaw** [comment]
Dear diary,

I've become best friends with **C++20 concepts**. It's the key for slim declarations for "very generic" code. Also enables some **very natural overwrite resolution** for the 'Buffer'-specialisations.
Have created a concept for each colortype in `/modm/ui/color/concept.hpp` and use them all around.

Readability and refactor-ability improves dramatically.

**Comment by salkinium** [comment]
I'm generally positively impressed by these changes and looking forward to the finished PR, particularly since there are many very cool improvements in here! 😍

However, I've completely lost the overview of this PR and GitHub is struggling to show me the whole diff, due to +6,742 −14,976 changes, so I'm struggling to review it… There are also too many commits for me to click through, so I cannot review commit by commit either.

I think we need to split this up a little, are there changes you can pull out into separate PRs that are more independent? There's no time pressure, just want to let you know that I'm willing to review just not really able to.

**Comment by TomSaw** [comment]
Quote @salkinium, 30 .Juli 2021 in #660 😜 

> Just make one big PR and partition your changes into separate commits

Also didn't expect such a code explosion - It's much fun, a great learning subject and ongoing story: Let's keep #665 as reference and merge proven pieces step bz step! Here's Nr.1 #690 

> are there changes you can pull out into separate PRs that are more independent

 Yes. I have renamed the ordered list in my opening message: <strike>Planned commits</strike> -> Planned PRs.

**Comment by TomSaw** [comment]
I've created PRs for environmental changes @salkinium so we get the table as clean as possible to concentrate on the real chunks. See section **Roadmap** in this PRs opening message.

**Comment by TomSaw** [comment]
> I think we need to split this up a little, are there changes you can pull out into separate PRs that are more independent? There's no time pressure, just want to let you know that I'm willing to review just not really able to.

Closed because PR is way too big. First fragments are in review and you find the rest of the code in my origin [feature/rewrite-graphic](https://github.com/TomSaw/modm/tree/feature/rewrite-graphic)

**Pull request closed without merging**
