### PR TITLE
[stm32] Flash driver enabled for F1 family

### PR DESCRIPTION
**Pull request by asmfreak**
This PR enables Flash driver for F1 medium and small chips

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Nice! Do you want to add an [example to measure speed](https://github.com/modm-io/modm/blob/develop/examples/nucleo_f446re/flash/main.cpp)?

**Comment by asmfreak** [comment]
Yeah! Working on it.

**Comment by asmfreak** [comment]
How to detemine if the device is "medium" or "high" density from `module.lb`?

**Comment by salkinium** [comment]
Only through the target identifier atm

**Review by salkinium — APPROVED** [review]
Thanks! Ready to merge?

**Pull request merged**
