### PR TITLE
Ethernet for STM32F4

### LINKED ISSUE #583: Ethernet freertos_tcp on f439zi nucleo not working
Hello,
I will append my experience here, even though there is an issue for that already:
 * https://github.com/modm-io/modm/issues/447

### Preamble
I got @mikewolfram 's `lan8720a` phy driver and the corresponding example (using freertos_tcp) working with the f767zi nucleo board after changing some of the PHY pins hardcoded in the example he gave. 

### Getting There
After that, I tried to get it running on the f439zi but was unable to do so. After some hours of experimenting with the freertos network scheduler (RTOS_IP) and ethernet stack, i finally ended inside the event loop (controlled by freertos ip stack) of the `lan8720a` ([see here](https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L421)) which should eventually handle arp requests coming from another laptop connected to the board via ethernet. 

### The Problem
The [event loop](https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L421) handles events constantly (as expected), but every event is regarded as a NOP `modm::platform::eth::Event::None` and therefore ignored. Which means that the feeding function, responsible for setting proper events, is not working properly. 

As it turns out, the producer function is [this](https://github.com/modm-io/modm/blob/develop/ext/aws/modm_lan8720a.cpp#L623-L650) ISR 
```cpp
MODM_ISR(ETH)
{
	using modm::platform::eth;
	using modm::ethernet;

	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	EMAC::InterruptFlags_t irq = EMAC::getInterruptFlags();
	EMAC::acknowledgeInterrupt(irq);

	if (irq & (eth::InterruptFlags::Receive | eth::InterruptFlags::ReceiveBufferUnavailable)) {
		ethernet::isrEvent |= eth::Event::Receive;
		if (ethernet::emacTaskHandle) {
			vTaskNotifyGiveFromISR(ethernet::emacTaskHandle, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
		}
	}
	if (irq & (eth::InterruptFlags::Transmit)) {
		ethernet::isrEvent |= eth::Event::Transmit;
		if (ethernet::emacTaskHandle) {
			vTaskNotifyGiveFromISR(ethernet::emacTaskHandle, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
		}
	}

	if (EMAC::getInterruptFlags() & eth::InterruptFlags::AbnormalIrqSummary) {
		// not used yet
	}
}
```

My test have shown (led blinky, event chain debugging) that this specific ISR is not called properly. 
Is there something you guys can tell me about the differences between the interrupt handling (mainly ethernet-DMA interrupts) ?

### Other Stuff

* I tried checking registers for interrupts, dma and others to see if any flags have changed but it seems that these chips(f4 & f7) are equal in that matter
* we have an internal issue where this errata was evaluated, but we could not find anything in particular which could be problematic: https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf

### End

Thank you for reading, maybe someone can help

### PR DESCRIPTION
**Pull request by rleh**
Based on the awesome work done by @mikewolfram in #466, but now enabled (and debugged) for STM32F4.
Thanks to @jnewcomb and @kikass13 for giving hints and testing in #583!

I don't want the current solution with the modified linkerscript to get merged, but opening this Draft PR already to further discuss here about the options and later code.

### CODE REVIEW

**Comment by jnewcomb** [comment]
@rleh Are any updates required to stop lbuild from complaining?
modm\ext\aws\module.lb
modm\src\modm\platform\eth\stm32\module.lb

A copy of my 'rough' notes below covering the errors I got and the fixes I made.. (Sorry.. I'm presently learning how to use git!..)
```
Added to "C:\Projects\modm\modm\examples\nucleo_f429zi\freertos_plus_tcp\project.xml"
<module>modm:freertos:tcp:lan8720a</module>

lbuild gives us:
ERROR: Cannot resolve name 'modm:freertos:tcp:lan8720a' of type Module!

Current project configuration:
ConfigNode(filename='project.xml')
╰── ConfigNode(filename='../../../src/modm/board/nucleo_f429zi/board.xml')
    ╰── ConfigNode(filename='../../lbuild.xml')


THIS IS BECAUSE...
It is included in "C:\Projects\modm\modm\stm32f767zit6.txt"

    ├── Module(modm:freertos)   FreeRTOS
    │   ├── Option(frequency) = 1000 in [4 ... 1000]   Context switch frequency in Hz
    │   ╰── Module(modm:freertos:tcp)   FreeRTOS+TCP
    │       ╰── Module(modm:freertos:tcp:lan8720a)   a:FreeRTOS-Plus-TCP Ethernet via LAN8720A

But NOT in "C:\Projects\modm\modm\stm32f429zit6.txt"
    ├── Module(modm:freertos)   FreeRTOS
    │   ├── Option(frequency) = 1000 in [4 ... 1000]   Context switch frequency in Hz
    │   ╰── Module(modm:freertos:tcp)   FreeRTOS+TCP


The stm32f767zit6 generated code has this:
C:\Projects\modm\modm\examples\nucleo_f767zi\ethernet\modm\ext\freertos_plus_tcp


So...
Update module to allow F4 and F7
IN:
C:\Projects\modm\modm\ext\aws\module.lb
CHANGE:
if device.identifier.family not in ["f7"]:
TO:
if device.identifier.family not in ["f4", "f7"]:

This generates a different warning..
ERROR: Cannot resolve dependency ':platform:eth' of Module(modm:freertos:tcp:lan8720a)!
In file '../../../ext/aws/module.lb:22' in function 'prepare':
    def prepare(self, module, options):

THIS IS BECAUSE...
In:
C:\Projects\modm\modm\ext\aws\module.lb
There is a dependancy:
module.depends(":platform:eth", ":driver:lan8720a")
That is not included in the F4...

So..
Add ":platform:eth" for F4 platforms
IN:
"C:\Projects\modm\modm\src\modm\platform\eth\stm32\module.lb"
CHANGE:
if device.identifier.family not in ["f7"]:
TO:
if device.identifier["family"] not in ["f4", "f7"]:
```

**Comment by rleh** [comment]
> C:\Projects\modm\modm\ext\aws\module.lb
> CHANGE:
> if device.identifier.family not in ["f7"]:
> TO:
> if device.identifier.family not in ["f4", "f7"]:
> [...]
> CHANGE:
> if device.identifier.family not in ["f7"]:
> TO:
> if device.identifier["family"] not in ["f4", "f7"]:

That are exactly the changes done in commit 0d3be64 (in this pull request).
You should be able to `git checkout` (or with modern git: `git switch`) to my branch (or only cherry-pick the commit) if you ad the [forked repo](https://github.com/DroidDrive/modm/tree/feature/ethernet_stm32f4) as an additional [git remote](https://git-scm.com/docs/git-remote).

**Comment by jnewcomb** [comment]
Doh, told you I was a git noob, thanks for the tips.
~TortoiseSVN is my 10-year crack habit .. and I know I should come off it!

I still can't see the edits to:
modm\ext\aws\modm_lan8720a.cpp
(or is that intentional / awaiting comments?)

It's possible to template and keep a conditional fastdata for F7 - other ports seem to do this.. I guess it reduces DMA arbitration if other DMAs transactions share the SRAM.
Not sure about 32 byte alignment.. I swapped to 4 in line with other DMA buffers.

**Comment by salkinium** [comment]
> Not sure about 32 byte alignment.. I swapped to 4 in line with other DMA buffers.

The 32-BYTE alignment is correct, but it seems like the STM32F7 only has a 64-bit bus, so it could possibly be 16B aligned too. It's probably best to leave it like that, potentially wasting 31B is not the issue with a few kB of buffer required for the Ethernet frames anyways.

**Comment by rleh** [comment]
@salkinium I copied your changes that moves the stack into DMA capable memory from #743 into commit 51438e8ef.

**Comment by rleh** [comment]
The example now works on my Nucleo-F439ZI board 🥳

**Review by salkinium — CHANGES_REQUESTED** [review]
Please apply this patch to the linker change commit: https://github.com/salkinium/modm/commit/7f9e9db686a73031c19a5d0b13705f3a59562b27

**Review by salkinium — APPROVED** [review]
Awesome!

**Pull request merged**
