### PR TITLE
[docs] Enable dark-mode on modm.io and docs.modm.io

### PR DESCRIPTION
**Pull request by salkinium**
- [x] Enable darkmode for mkdocs based on user preference.

- [x] Enable darkmode for Doxypress based on user preference.

cc @rleh

### CODE REVIEW

**Comment by salkinium** [comment]
Neither Doxypress nor Doxygen have built-in dark themes, so I'm using my extremely advanced CSS skillz to hack something together based on what other people have done… 😒

**Comment by salkinium** [comment]
I've copied over the MIT licensed CSS from https://github.com/maJerle/doxygen-dark-theme, which already gets us 95% there for the Doxypress theme, and it is somewhat beautiful even.

~However, there are some differences that I'm too dumb to fix: the header tab bar and the alternating list css. Nothing I tried changes these colors (even in the original css), I must be doing something very wrong. I'll continue trying, but this is really not my jam.~

**Comment by salkinium** [comment]
Never mind, I discovered `!important`.

**Comment by rleh** [comment]
One question: Is the dark theme the only theme available or is there a switch to enable/disable it?

**Comment by salkinium** [comment]
Mkdocs changes based on your web browser preference.
But the Doxypress and docs homepage CSS settings are definitely hardcoded.

**Comment by salkinium** [comment]
Lemme check how the user preference CSS thingy works, maybe it's easy to adapt.

**Comment by salkinium** [comment]
> Is the dark theme the only theme available or is there a switch to enable/disable it?

It now supports both by just wrapping it into: `@media (prefers-color-scheme: dark) { ... }`.
Let me check if I can add an explicit switch somewhere.

**Comment by salkinium** [comment]
> Let me check if I can add an explicit switch somewhere.

Apparently there's a toggle for MkDocs, but it's only available for 10€/month sponsorships. Meh.
https://squidfunk.github.io/mkdocs-material-insiders/setup/changing-the-colors/#color-palette-toggle

For Doxypress CSS we have to implement a toggle ourselves… but I'm not motivated to do it. I would assume that people using dark mode in their OS setting are fine with getting dark mode websites.
https://jouni.kantola.se/blog/2020-02-29/dark-mode-toggle/

**Comment by salkinium** [comment]
I've tested this on Safari with both prefers-color-scheme light/dark.

**Review by rleh — APPROVED** [review]

**Comment by salkinium** [comment]
Thanks, I'll test it first with a develop-dark-theme branch before I mess something this big up.

**Review by rleh — CHANGES_REQUESTED** [review]
grafik

Black text on dark-grey background. Should be changed...

**Comment by salkinium** [comment]
Hm, not digging the dark blue or whatever that is either.

**Comment by rleh** [comment]
The SVG graphics are also an issue...
grafik

**Comment by salkinium** [comment]
I fixed the PNG (yes!) graphics by inverting them. It looks ok, but most importantly it doesn't require two sets of graphics (which I have no clue how to get).



The search field is in a iframe, and Doxypress did not add the custom CSS to that iframe. 🤦‍♂️



So I had to hack it with some Javascript. It's not elegant but it works. I'll open an issue with Doxypress later.

**Comment by salkinium** [comment]
Found another issue with the dependency graphs in the module docs:



Good thing we have the `develop-*` build rule!

**Comment by salkinium** [comment]
This is fixed now too:

**Comment by salkinium** [comment]
Also inverted these and removed the inaccessible CircleCI reference.

**Comment by rleh** [comment]
> PNG (yes!) graphics

Wait, all this graphics are PNG? Oh no...

**Review by rleh — APPROVED** [review]

**Pull request merged**
