### PR TITLE
[stm32] Fix [[nodiscard]] for Can::initialize()

### PR DESCRIPTION
**Pull request by chris-durand**
Put the [[nodiscard]] attribute in the right location.

### CODE REVIEW

**Review by rleh — APPROVED** [review]
Thanks :+1:

**Comment by chris-durand** [comment]
Here we get the same linker error with gcc10 as in the C++20 pull request.
The line of code triggering it [looks a bit unsual](https://github.com/modm-io/modm/blob/develop/ext/aws/FreeRTOSConfig.h.in#L39):
`modm_extern_c uint32_t _ZN4modm8platform4fcpuE;`

(a C++ mangled name inside an extern "C" block to be also used from C files, where `modm_extern_c` is empty)

This is a definition, not a declaration when compiled as C. This should fail if this file is included in more than one translation unit.

**Comment by salkinium** [comment]
So it should be like this?

```c++
extern
#ifdef __cplusplus
"C" 
#endif
uint32_t _ZN4modm8platform4fcpuE;
```

**Comment by chris-durand** [comment]
I would have suggested that, but when I looked closer I didn't find another definition (see #523). We might have to add one in a .c/.cpp file.

**Comment by rleh** [comment]
All CircleCI tests have passed, ~but for some reason Github does not know about it~.

**Pull request merged**
