### PR TITLE
Added NACKIE flag to read and write operations

### PR DESCRIPTION
**Pull request by nesos**
The read and write operations are missing the NACK interrupt enable flag. This causes devices to be trapped in an endless loop when the addressed device is not responding.
In this case no interrupt will be raised, the transaction will not be detached and stays busy forever.

I enabling the NACK interrupt when starting the transaction is fixing this issue

### CODE REVIEW

**Comment by salkinium** [comment]
Is there also a NACKIE that needs to be enabled for the non-extended STM32 driver?

**Comment by nesos** [comment]
> Is there also a NACKIE that needs to be enabled for the non-extended STM32 driver?

I haven't checked that. I'm currently working only with the STM32F042K6. I'll check this later tonight on on a STM32F411 board

**Comment by nesos** [comment]
The problem on getting the system stuck when trying to read from I2C nodes that don't respond does not appear on the non-extended master driver. So no need to change on that part.

**Comment by salkinium** [comment]
Great!

Can you rebase your commit so I can fast forward develop?

**Comment by nesos** [comment]
> Great!
> 
> Can you rebase your commit so I can fast forward develop?

Done!

**Comment by salkinium** [comment]
Thanks!

**Pull request merged**
