### PR TITLE
adding support for usb exemple on STM32F072B-Disco

### PR DESCRIPTION
**Pull request by lukh**
Usb example is running on a disco f072,

### CODE REVIEW

**Comment by lukh** [comment]
I have one question,
The usb clock is set up by default on the HSI48, instead of the PLL, (which make it work with the nucleo booard)

Should we add the option, in rcc, to change the usb clock ?

I started the work in rcc.hpp.in, l144
`	
// enum class
// UsbClockSource : uint32_t
// {
// 	Hsi48 = RCC_CFGR3_USBSW_HSI48,
// 	Pll = RCC_CFGR3_USBSW_PLLCLK
// };
`

But not sure about how to integrate properly in modm generator.. (and if it is necessary) (but i guess it  it is)

Bests

**Review by salkinium — CHANGES_REQUESTED** [review]
You need to add the `:platform:usb` module as a dependency to the F071 board `module.lb`, otherwise the `modm::platform::UsbFs` won't be available for examples that do not use the USB stack.

**Comment by salkinium** [comment]
> Should we add the option, in rcc, to change the usb clock ?

If I read the [User Manual](https://www.st.com/resource/en/user_manual/dm00099401-discovery-kit-for-stm32f0-series-microcontrollers-with-stm32f072rb-stmicroelectronics.pdf) correctly, the crystal in not populated and neither is SB19 to connect MCO from the ST-Link. So we have to use the internal clock anyways, and the accuracy is probably not better with the PLL from HSI8 compared to the HSI48.


So… meh?

**Review by salkinium — APPROVED** [review]
I will squash your commits into one and merge.

**Comment by lukh** [comment]
Great ! Thanks !

**Pull request merged**
