### PR TITLE
Adds basic support for STM32F4XX boards from DevEBox

### PR DESCRIPTION
**Pull request by strongly-typed**
Support for these STM32F4 boards
* https://stm32-base.org/boards/STM32F407VET6-STM32F4XX-M
* https://stm32-base.org/boards/STM32F407VGT6-STM32F4XX-M

### CODE REVIEW

**Comment by strongly-typed** [comment]
Shall the examples also be added to the CI?

**Comment by salkinium** [comment]
> Shall the examples also be added to the CI?

Yes, always! Otherwise it will be forgotten in future refactorings.

**Review by salkinium — APPROVED** [review]
Very nice!

**Comment by salkinium** [comment]
I'll rebase on develop if you don't do it for me ;-P (The CI is a bit slow atm, due to congestion)

**Pull request merged**
