### PR TITLE
[wip] stm32h7 support

### PR DESCRIPTION
**Pull request by elrosch**

### CODE REVIEW

**Comment by salkinium** [comment]
Is there an example here to compile? What project.xml are you using?

**Comment by elrosch** [comment]
Hi of course. I just had it locally. Now added it to the examples directory.
See here: https://github.com/EvilEli/modm/tree/feature/stm32h7/examples/stm32h7/blink

**Comment by salkinium** [comment]
> blink.elf section `.heap1' will not fit in region `RAM'
> ld: region `RAM' overflowed by 200704000 bytes

Yeah, I don't know what your issue is, the RAM section only overflowed by a mere 200… MEGABYTE?!? 🤪

**Comment by salkinium** [comment]
The issue was that the memory layout is discontiguous, and thus the `RAM` supersection cannot span from `SRAM` though `SRAM{1..4}`. Considering that SRAM is 512kB, the other SRAM sections are probably meant more for various DMA and peripheral use, rather than for generic application software use, so this should be fine. However the size reporting code is assuming that the `RAM` section contains *all* available RAM and thus reports over 100%. Ah well…

```
 $ scons
Linking········ blink.elf
Memory usage··· blink.elf
Program:   1.5 KiB (0.1% used)
(.build_id + .fastcode + .fastdata + .hardware_init + .rodata +
 .table.copy.intern + .table.heap + .table.zero.intern + .text + .vector_rom)

Data:      3.0 KiB (0.3% used) = 32 B static (0.0%) + 3072 B stack (0.3%)
(.bss + .fastcode + .stack)

Heap:      1.0 MiB (112.9% available)
(.heap + .heap0 + .heap1 + .heap2 + .heap3 + .heap4 + .heap5)
```

**Comment by salkinium** [comment]
This was a such a very obscure bug, it would have taken an unreasonable amount of time for you to find it, so good on you for opening an issue, I hope this unblocks you! 🥳

**Comment by salkinium** [comment]
@EvilEli did this help you get unblocked?

**Comment by elrosch** [comment]
Yes thanks a lot for your help.
Unfortunately I haven't found the time to test it yet.
I guess I will have to play around with it anyways so feel free to close the PR.

**Comment by strongly-typed** [comment]
Just to let you both know: I just received an STM32H743VIT6 board and tried to [rebase](https://github.com/strongly-typed/modm/tree/feature/stm32h7) @EvilEli's branch.

I was wondering: In 

https://github.com/modm-io/modm-devices/commit/6173f0c39a02f8b1ca88b6e28b26e8ad17ac5736#diff-ae26251e96d00d8a2ddda82cae05d74eL35

the RAM was renamed from `sram` to `d1_sram` for H7 devices which does not match

[stm32/linkerscript/stm32_dccm.ld.in](https://github.com/modm-io/modm/blob/develop/src/modm/platform/core/stm32/linkerscript/stm32_dccm.ld.in#L33)

anymore.

@salkinium When you mentioned [hardcoded](https://github.com/modm-io/modm/issues/378#issuecomment-614239918) you meant something else?

**Comment by salkinium** [comment]
The memory layout in H7 is fairly involved, I thus changes the naming to make it consistent with the clock/power architecture instead of the inconsistent ST naming. You will have to add a new linkerscript, probably based off the idtcm one.

**Comment by salkinium** [comment]
But to be clear: modm-devices may simply be wrong, since the memory is manually added by me and I do make mistakes.

**Comment by salkinium** [comment]
Continued in #652.

**Pull request closed without merging**
