### PR TITLE
[CI] Aarch64/arm64 Ubuntu Testing

### PR DESCRIPTION
**Pull request by rleh**
Run tests on [Travis CI ARM64 infrastructure](https://docs.travis-ci.com/user/multi-cpu-architectures/) ([Amazon AWS Graviton](https://aws.amazon.com/de/ec2/graviton/)).
Useful for e.g. Raspberry Pi and other upcoming ARM-based desktop/server platforms.

- [x] Test script
- [x] Fix errors

### CODE REVIEW

**Comment by rleh** [comment]
Seems to catch two issues.

Hosted: (Already fixed)
```
modm/src/modm/architecture/detect.hpp:228:3: error: #error "Couldn't determine target CPU!"
228 | # error "Couldn't determine target CPU!"
```

ARM Cortex-M:
```
Linking········ build/release/blink.elf
scons: building terminated because of errors.`_sbrk_r' referenced in section `.text' of /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/lib/thumb/v7-m/nofp/libc_nano.a(lib_a-nano-mallocr.o): defined in discarded section `.Heap_is_not_implemented!__Please_include_the__modm:platform:heap__module_in_your_project!' of build/release/modm/libmodm.a(no_heap.o)
`_sbrk_r' referenced in section `.text' of /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/lib/thumb/v7-m/nofp/libc_nano.a(lib_a-nano-mallocr.o): defined in discarded section `.Heap_is_not_implemented!__Please_include_the__modm:platform:heap__module_in_your_project!' of build/release/modm/libmodm.a(no_heap.o)
`_sbrk_r' referenced in section `.text' of /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/lib/thumb/v7-m/nofp/libc_nano.a(lib_a-nano-mallocr.o): defined in discarded section `.Heap_is_not_implemented!__Please_include_the__modm:platform:heap__module_in_your_project!' of build/release/modm/libmodm.a(no_heap.o)
collect2: error: ld returned 1 exit status
```

**Comment by rleh** [comment]
The `_sbrk_r`/heap issue seems to be related to the packaged GCC [`gcc-arm-none-eabi`](https://packages.ubuntu.com/focal/gcc-arm-none-eabi) from Ubuntu 20.40. I have seen this error also on a x86_64-based Ubuntu a few days ago.

**Comment by salkinium** [comment]
The RPi example should also be tested. I think you need to install `<wiringPi.h>` for that somehow?
```yml
  - (cd examples && ../tools/scripts/examples_compile.py rpi)
```

**Comment by rleh** [comment]
WTF, why does this happen:

```c++
uint32_t val = 0xdeadbeef; modm::toBigEndian(val) == 0;
modm::toBigEndian(static_cast<uint32_t>(0xdeadbeef)) == 0;
modm::toBigEndian(static_cast<int32_t>(0xdeadbeef)) == 0;
modm::fromBigEndian(static_cast<uint32_t>(0xdeadbeef)) == 0;
modm::fromBigEndian(static_cast<int32_t> (0xdeadbeef)) == 0;
```

**Comment by salkinium** [comment]
> WTF, why does this happen:

Just checked the same issue: because in [`bit_operation.hpp`](https://github.com/modm-io/modm/blob/develop/src/modm/math/utils/bit_operation.hpp#L73-L205) the `MODM_CPU_ARM` macro is too generic and doesn't distinguish between ARMv7-M and ARMv7-A. These macros should be named `MODM_CPU_ARMV7_M` and `MODM_CPU_ARMV7_A`. (and also `MODM_CPU_ARMV6_M`, and in future `MODM_CPU_ARMV8_M`).

**Comment by rleh** [comment]
The question here is not whether run on ARM v6, v7, v7-A or so, but whether the CPU runs in 64-bit mode (only available, but not mandatory with ARMv8-*).

**Comment by salkinium** [comment]
> whether the CPU runs in 64-bit mode

It just needs to choose the Cortex-M optimization only on Cortex-M. The fallback pure software implementation works fine too, and may also even be optimized.

**Review by salkinium — APPROVED** [review]
Thanks!

**Comment by henrikssn** [comment]
Thanks! I actually stumbled upon the `_sbrk_r ` issue already but assumed I had installed a broken compiler.

Aarch64 contributions to #439 are highly welcome, now that it is required by the CI :)

**Comment by rleh** [comment]
A bit off-topic, but interesting: Apparently you can also use non-x86 actions in Github: https://github.com/uraimo/run-on-arch-action
With [Azure Pipelines](https://azure.microsoft.com/de-de/services/devops/pipelines/) this seems to be possible as well.

**Comment by salkinium** [comment]
> non-x86 actions

I was briefly ecstatic until I realized you weren't talking about https://hwut.de 😉.

**Comment by rleh** [comment]
> https://hwut.de/

My plan is to bring [hwut.de](https://hwut.de/) into productive use in October (after exams and vacations) and also to integrate it into modm!

**Pull request merged**
