### PR TITLE
[stm32] Add calibration for F1 ADC

### PR DESCRIPTION
**Pull request by chris-durand**
Add calibration function for F1 ~~, F2, F4, F7~~ ADC. Successfully tested on F105 hardware. Running the calibration improved the accuracy significantly.

### CODE REVIEW

**Comment by chris-durand** [comment]
The calibration functionality seems to be only present on F1 …

**Comment by chris-durand** [comment]
@salkinium Travis CI is not working again.

**Review by salkinium — APPROVED** [review]

**Comment by salkinium** [comment]
Please rebase on develop.

> @salkinium Travis CI is not working again.

Yes, Travis.org moved to travis.com or some bullshit like that. Someone™ needs to fix that…

**Comment by chris-durand** [comment]
> Please rebase on develop.

Sorry, I forgot. Was to distracted debugging wrong ADC measurements. Do we have to run the full HAL test again?

**Comment by salkinium** [comment]
> Do we have to run the full HAL test again?

No, I'll merge after the quick test passes

**Pull request merged**
