### PR TITLE
[hosted] Fix include of boost bind in serial_port.hpp

### LINKED ISSUE #506: [boost] placeholders (_1, _2, ...) in the global namespace is deprecated
```
/usr/local/include/boost/config/pragma_message.hpp:24:34: note: '#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.'
   24 | # define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
      |                                  ^~~~~~~
/usr/local/include/boost/bind.hpp:36:1: note: in expansion of macro 'BOOST_PRAGMA_MESSAGE'
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/local/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/local/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/local/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/local/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/local/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/local/include/boost/shared_ptr.hpp:17,
                 from /usr/local/include/boost/date_time/time_clock.hpp:17,
                 from /usr/local/include/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from /usr/local/include/boost/asio/time_traits.hpp:23,
                 from /usr/local/include/boost/asio/detail/timer_queue_ptime.hpp:22,
                 from /usr/local/include/boost/asio/detail/deadline_timer_service.hpp:29,
                 from /usr/local/include/boost/asio/basic_deadline_timer.hpp:25,
                 from /usr/local/include/boost/asio.hpp:25,
                 from modm/src/modm/platform/uart/serial_port.hpp:20,
                 from modm/src/modm/platform/uart/serial_port.cpp:14:
```

We might run into future errors as it is deprecated.

But it seems to be internal to boost 🤔

```
boost: stable 1.74.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.74.0 (14,695 files, 524.4MB) *
  Poured from bottle on 2020-10-20 at 22:01:06
```

### PR DESCRIPTION
**Pull request by chris-durand**
Fixes #506

### CODE REVIEW

**Comment by chris-durand** [comment]
@salkinium CI is broken: `lbuild: command not found` for MacOS

**Comment by rleh** [comment]
@chris-durand Python version on MacOs has changed from 3.8 to 3.9.

Could you change [this line](https://github.com/modm-io/modm/blob/develop/.github/workflows/macos.yml#L24):
```diff
-echo "/Users/runner/Library/Python/3.8/bin" >> $GITHUB_PATH
+echo "/Users/runner/Library/Python/3.9/bin" >> $GITHUB_PATH
```

**Review by rleh — APPROVED** [review]
Thanks :+1:

**Comment by rleh** [comment]
@strongly-typed already fixed the MacOS-CI error in a99113b.

**Comment by chris-durand** [comment]
> @strongly-typed already fixed the MacOS-CI error in [a99113b](https://github.com/modm-io/modm/commit/a99113b0d5a9d935bd3d0cc2143bbdd706c9d89d).

Ok, I removed the commit again.

**Comment by salkinium** [comment]
You may rebase for CI.

**Review by salkinium — APPROVED** [review]

**Comment by strongly-typed** [comment]
Thank you! Works like a charm in my project (just works for me ;-). So LGTM!

**Pull request merged**
