### PR TITLE
Separate XPCC system_tools from :build:scons module

### PR DESCRIPTION
**Pull request by salkinium**
This adds the submodule `:communication:xpcc:generator` which copies the `tools/system_design` python tools to generating the XPCC communication.

Before the `:build:scons` module copied these files iff the `:build:scons:xpcc.source` option was set, which was weird when using a custom SConscript, and having to set this to a `dummy.xml` to get these files copied.

This also fixes duplicate compilation of the generated XPCC sources.

- [x] Rename the `system_design` folder to something more xpcc related, `xpcc_generator`?
- [x] Rename the `communication` examples to `xpcc`.

cc @dergraaf @rleh @mhthies @chris-durand

### CODE REVIEW

**Review by salkinium — COMMENTED** [review]
I'm happy with this.

**Comment by rleh** [comment]
But the CI job *unittests* is unhappy:
```
python2: can't open file 'tools/system_design/builder/system_layout.py': [Errno 2] No such file or directory
```

**Comment by salkinium** [comment]
> But the CI job unittests is unhappy

Too much renamin', too little ack-grep'in.

**Comment by salkinium** [comment]
> fatal error: error writing to /tmp/ccpawS2W.s: Cannot allocate memory

CircleCI sometimes fails to allocate enough memory.

> Too many levels of symbolic links

And GitlabCI is weird too.

Le Sigh…

**Pull request merged**
