### PR TITLE
Add option to generate compilation db

### PR DESCRIPTION
**Pull request by asmfreak**
CLion cannot use CMakeLists.txt, generated by modm due to custom build locations.
To enable ourselves to use CLion in projects this little addition is needed.
See [this example project](https://github.com/ASMfreaK/modm-example-clion-project) to understand how it is used.

### CODE REVIEW

**Review by salkinium — DISMISSED** [review]
Thanks!

**Comment by salkinium** [comment]
Compilation Database is something I would like to generate directly from a new submodule of `modm:build`, but didn’t find example code for it. I guess I have to check out the CMake or SCons source code. See also:  https://github.com/modm-io/modm/issues/125#issuecomment-442077244

**Comment by asmfreak** [comment]
As for SCons see how [mongo](https://github.com/mongodb/mongo/blob/eea0ef850ef7f07e354a466e011b39ab518a5254/site_scons/site_tools/compilation_db.py) implemented this. Maybe we can import that code directly (if license allows)?

**Comment by salkinium** [comment]
I’m mobile-only due to GPN19, so I’m not expecting any further features for this PR, just need my laptop. 😛 (just in case you were wondering why I’m not merging this)

**Comment by asmfreak** [comment]
I seriously needed comp_db in scons builds, so I pulled mongo's design I linked earlier. I also wanted to use `modm:unittest` to test my code, which have lead to some backward-compatible changes in `scons/module.lb` and associated files.
If it's too much, I'll revert it back.
Also licensing question - can we use mongo's solution? I've left copyright intact and added my copyright as I made changes to their code to prevent scons from crashing with `NotImplementedError`.

**Comment by salkinium** [comment]
Hm, the GPL is technically compatible with MPL, I just don't really want it in the codebase. But I do see the value this adds to SCons.

I like the unittest changes, however, the SCons unittest tool is just a glorified Python script with a few regexes, that I would like to extract into a stand-alone small Python script.

I'm going to have a look at these two issues. Is it ok for you to keep these changes a little longer in your fork?

**Comment by asmfreak** [comment]
It's ok with me.
I'd be happy to see it merged some day.

чт, 6 июн. 2019 г. в 22:56, Niklas Hauser <notifications@github.com>:

**Comment by asmfreak** [comment]
The `compilation_db` tool included in this PR for scons no longer works. Some updates in modm and/or scons rendered it unuseable.

**Comment by salkinium** [comment]
Ok, lemme check what I broke this time.

**Comment by asmfreak** [comment]
I don't know scons well enough. I blame the script.
I even tried [an updated version from mongo](https://github.com/mongodb/mongo/blob/master/site_scons/site_tools/compilation_db.py).
I doesn't break, but it does not output a single thing, just `[]`
It generated *some* output, once I've put it like this
```
...
sources.append(env.InfoGit(with_status=True))
sources.append(env.InfoBuild())
# Long comment by lbuild
# ...
env.Tool("compilation_db")
env.BuildTarget(sources)
env.Alias("compilation_db", env.CompilationDatabase("compile_commands.json"))
```

It outputted only lines for main and files with buildinfo.

**Comment by salkinium** [comment]
I'm trying it in the `example/nucleo_f411re/blink` and it only outputs how to compile `main.cpp`, nothing about modm.

**Comment by salkinium** [comment]
>  it only outputs how to compile main.cpp, nothing about modm.

Cos I'm stupid and this needs to be placed at the end of the tools in the modm/SConscript, but BEFORE the static library is compiled. Ugh, this is horrible.

**Comment by salkinium** [comment]
Specifically the `env.Tool("compilation_db")` needs to be added after the `settings_buildpath` tool to work.

**Comment by salkinium** [comment]
Just to clarify: Are you able to compile your code with CompilationDB? Cos it's missing not only assembly files (`.s`, `.sx`, `.S`), but also the linker steps with our custom linkerscripts and linkflags.

**Comment by asmfreak** [comment]
I don't need ConpilationDB to compile code. I only use it to get code completion and code insight for IDE. It was working ok  since I created this pull request, but stopped working after I updated modm. I even thought of running scons under strace, logging execve's and reformatting this log into CompilationDB json. I use scons for hosted linux compilations and hosted unit tests. I might just migrate that code to use cmake

**Comment by salkinium** [comment]
Ok, so here's the deal. I'll create a seperate `modm:build:compilation_db` module, that generates the CompilationDB manually. The MongoDB tool isn't dealing with Assembly files and Linking, and I would like to see this as a proper build system, especially since many more IDE start to support it.

In the meantime, I've added a simple commit on this branch, that re-adds this tool correctly: https://github.com/salkinium/modm/tree/feature/compilation_db

**Comment by salkinium** [comment]
I'm closing this in favor of #293.

**Pull request closed without merging**
