### PR TITLE
Replace CircleCI with Github Actions (self-hosted runners)

### PR DESCRIPTION
**Pull request by rleh**

### CODE REVIEW

**Comment by rleh** [comment]
Duplicate of #588, but I want to test self-hosted runners in parallel...

**Comment by salkinium** [comment]
dafuq why is this so fast?!?

**Comment by rleh** [comment]
grafik

**Comment by rleh** [comment]
grafik

The last 15 minutes there are not enough jobs to fully load the server:
grafik

**Comment by salkinium** [comment]
I'm not sure if there was a miscommunication, but I'm still very interested in the speedup of self-hosting, but it's perhaps too much work?

**Comment by rleh** [comment]
Using own runners means a lot of effort for us/me and brings only small performance improvements.
Therefore I will not continue this for now, I think there are currently more interesting features (e.g. hwut... 😆 ).

**Comment by salkinium** [comment]
> Using own runners means a lot of effort for us/me and brings only small performance improvements.

Yes, that's also the impression I got. Thanks for trying this out though.

> I think there are currently more interesting features (e.g. hwut... 😆 ).

HECK YEAH!!!

**Pull request closed without merging**
