### PR TITLE
Doxypress API documentation on https://docs.modm.io/ with fixes

### PR DESCRIPTION
**Pull request by salkinium**
#281 with fixes relating to module selection.

cc @rleh

### CODE REVIEW

**Comment by dhebbeker** [comment]
https://docs.modm.io/ used to work two weeks ago. Now it redirects to #332. 😢

**Comment by rleh** [comment]
It's currently broken. Maybe I will fix it tomorrow.

**Comment by rleh** [comment]
@dhebbeker https://docs.modm.io/ now works again.

**Comment by dhebbeker** [comment]
Thanks!

**Pull request closed without merging**
