### PR TITLE
[stm32] add Half Transfer handler for dma

### PR DESCRIPTION
**Pull request by lukh**
I would love to add ISR handler for the Half Transfer Interrupt on DMA, for the stm32 serie
It looks like some of the STM32 are not passing UI

Don't know (yet) how to filter out the HT flag

### CODE REVIEW

**Review by chris-durand — COMMENTED** [review]
Nice! I have quickly added the half transfer interrupt for all DMA types. Let's see what the CI says.

**Review by chris-durand — APPROVED** [review]
Thanks! Could you rebase and squash the commits into one?

**Comment by lukh** [comment]
I am sorry, not used to this workflow, I need your help on this one...

**Comment by chris-durand** [comment]
> I am sorry, not used to this workflow, I need your help on this one...

I have done it.

**Pull request merged**
