### PR TITLE
[lbuild] Warn if submodules are not up-to-date

### PR DESCRIPTION
**Pull request by salkinium**
Adds a more comprehensive check for distiguishing between missing submodules (error) and out-of-date submodules (warning).

cc @se-bi

### CODE REVIEW

**Comment by se-bi** [comment]
Does it through an error, if it is out of sync? 

Does it distinguish between old state and something to be tested, if that occurs often with the submodules?

**Comment by salkinium** [comment]
> Does it through an error, if it is out of sync?

No, since that would be quite annoying for me.

> Does it distinguish between old state and something to be tested, if that occurs often with the submodules?

No, it only checks if the submodule hexsha is the current checkout hexsha.

**Comment by salkinium** [comment]
I could probably add a way to fail when calling lbuild verbosely with `lbuild -v discover`, would that help? (this would be quite fragile, how often do you call `lbuild -v`?)

**Comment by se-bi** [comment]
Mhm, sorry. I had a comment  on a different Issue in mind.

Warning is fine, user must just find it. :stuck_out_tongue_closed_eyes:

**Comment by se-bi** [comment]
> I could probably add a way to fail when calling lbuild verbosely with `lbuild -v discover`, would that help? (this would be quite fragile, how often do you call `lbuild -v`?)

The `lbuild discover` should not fail, but big red warning at the end would be an option :wink:

**Comment by salkinium** [comment]
> The lbuild discover should not fail, but big red warning at the end would be an option 😉

Hm, I can only put it at the beginning for now (it's using barebone printf), since there isn't a lbuild API for checking the repo.lb validity. Maybe this is a good idea to add to the `init` function…

**Pull request merged**
