### PR TITLE
[example] Fixed 2 bugs in example/arduino_nano/color

### PR DESCRIPTION
**Pull request by TomSaw**
Fixed 2 bugs in example/arduino_nano/color
+
Took the chance to beautify other color-examples by adding Descriptor "HSV: " to output-stream.

### CODE REVIEW

**Comment by salkinium** [comment]
Ok, but let's squash them all into one commit please.

**Comment by TomSaw** [comment]
Squashing done.

**Review by salkinium — APPROVED** [review]

**Comment by salkinium** [comment]
Just as additional info: the CI has changed and will not auto-cancel builds anymore (we didn't find an easy way to fix this). This means for every commit you push the CI runs for ~12mins @ 13 jobs. Since we're running on the free plan, we're limited to 20 parallel jobs, so if you push a lot of commits you'll have to wait for a long time until the jobs become available.

**Comment by salkinium** [comment]
You can hopefully see the jobs queue here: https://github.com/modm-io/modm/actions

**Comment by TomSaw** [comment]
`You can hopefully see the jobs queue`
I see them and got this.
From now on i'll push only when there's a real benefit from it.
Being aware of squashing commits will also reduce clutter.

**Pull request merged**
