### PR TITLE
[cmake] Improve handling of tools, flags and actions

### LINKED ISSUE #269: Auto-generated CMake - Ubuntu 18.04
The auto generated cmake no longer compiles on ubuntu 18.04. The output from the build script on my computer can be seen here: https://justpaste.it/2wmyo

The auto generated cmake script works with commit: 20b145787ee8e695ad7dfd30ee4bb92d7aebcc9a

### PR DESCRIPTION
**Pull request by salkinium**
- [x] Only suffix compatible tools, make tool generation analog to SCons generator
- [x] Do not generate `.bin`, `.hex` and `.lss` files for hosted targets
- [x] Force set CMake compile flags in `modm.cmake`

Fixes #269.
cc @nicoBruhn can you check if these fixes work for you?

### CODE REVIEW

**Comment by nicoBruhn** [comment]
Still does not work. The compiler flags are overwritten when the project() is called because they are not cached internal.

**Comment by salkinium** [comment]
> Still does not work. The compiler flags are overwritten when the project() is called because they are not cached internal.

Unfortunately I cannot reproduce this issue, can you try a few things and to see what fixes things for you?

**Comment by salkinium** [comment]
I suspect this has something to do with https://github.com/modm-io/modm/pull/264 too.

**Comment by salkinium** [comment]
Closing this due to lack of reproducibility.

**Pull request closed without merging**
