### PR TITLE
[fix] fixed forgotten modm:blue-pill -> modm:blue-pill-f103

### PR DESCRIPTION
**Pull request by TomSaw**
This has grabbed my attention on CI builds so quickly fixed it.

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Thanks, I should check for warnings like these more often!

**Review by rleh — APPROVED** [review]

**Comment by salkinium** [comment]
What's with the commit message? That doesn't sound related to the lbuild alias warning?

```
[fix] fixed forgotten modm:blue-pill -> modm:blue-pill-f103

Previously, if the compiler was not on PATH, shutil.which would return
None and the error from "realpath" would be:

    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by chris-durand** [comment]
> What's with the commit message? That doesn't sound related to the lbuild alias warning?

@TomSaw Also, the commit author should probably be you and not @WasabiFan. I guess you accidentally amended [that commit](https://github.com/modm-io/modm/commit/78308b0d055049e7fca6e3a9576f32e21b41e17f).

**Comment by TomSaw** [comment]
OK is fixed - Thanks guys!

**Review by chris-durand — APPROVED** [review]
Thanks!

**Pull request merged**
