### PR TITLE
[ext] Update all submodules

### PR DESCRIPTION
**Pull request by salkinium**
In preparation of the Q2 release, I'm updating all submodules and testing them in hardware:

- [x] TinyUSB v0.9.0 -> v0.10.1
  - [x] Tested all STM32 examples in hardware
  - [x] Tested all SAMD examples in hardware
  - ~Add USB support to STM32L476VG Discovery board (no success yet)~
- [x] FatFs v0.14a -> v0.14b with slightly updated config
- [x] avr-stdlibc++ [pointed to a commit outside the repo](https://github.com/modm-io/avr-libstdcpp/commit/9c9a78) (!!!!)
- [x] cmsis-header-stm32: nothing interesting
  - [x]  L1 v2.3.1 -> v2.3.2
  - [x] F1 v4.3.2 -> v4.3.3
  - [x] F2 v2.2.4 -> v2.2.5
- [x] LVGL v7.11.0 -> v8.0.1
  - [x] Tested on F469 DISCO
  - [ ] Tested on L452 Nucleo

The remaining submodule have only very minor changes but they are still updated to simplify this process in future via `git submodule update --remote`.

### CODE REVIEW

**Comment by salkinium** [comment]
@rleh When you have time, could you test the LVGL example on the L452? (I plan to merge this PR on 30.6.)

**Comment by rleh** [comment]
> I plan to merge this PR on 30.6.

That should give me enough time to test the updated LVGL 👍🏽

**Comment by salkinium** [comment]
@rleh I'm going to merge this tomorrow morning (without L476 TinyUSB support). I assume LVGL to work fine, since it works on the F469.

**Comment by salkinium** [comment]
Even though CMSIS updated from v5.7.0 to v5.8.0 a few days ago I only noticed now and the changes to CMSIS-DSP are too large for me to integrate for this release. So I'm delegating this to the next release.

**Pull request merged**
