### PR TITLE
gitignore for vscode/codium ide

### PR DESCRIPTION
**Pull request by rleh**

### CODE REVIEW

**Review by salkinium — APPROVED** [review]

**Comment by salkinium** [comment]
Are you building/debugging with VSCode? If so, how is it integrated, how can modm be improved to provide better integration?

**Comment by salkinium** [comment]
Cherry-picked to develop manually. (Forgot to push your branch before pushing develop)

**Comment by rleh** [comment]
I have been using mainly [VSCodium](https://vscodium.com/) (Bloat- and Tracking-free version of VSCode) recently.
It works great and without modifications (except for the Microsoft C/C++ Plugin installed and configured to C11 and C++20) in a project with already generated `modm/` files.

```bash
cd modm/examples/nucleo_g474re/blink/
lbuild build

codium .  # Or if you prefer to click around in a GUI: File -> Open Folder -> ...

# and then run scons from my terminal (or the VSCodium integrated terminal)
scons -j8
```

If have used VSCodiums CMake plugin for other software, but not with modm yet.

**Comment by salkinium** [comment]
Cool, didn't know about VSCodium!

**Pull request closed without merging**
