### PR TITLE
[ci] Remove Python 2

### PR DESCRIPTION
**Pull request by strongly-typed**
Default to Python 3. I updated the docker container to run all scons scripts in Python 3 as well.

### CODE REVIEW

**Comment by strongly-typed** [comment]
See also modm-ext/docker-modm-build#5

**Review by salkinium — DISMISSED** [review]

**Comment by salkinium** [comment]
I'm not merging this until the GitHub CI is fixed.

**Comment by strongly-typed** [comment]
> I'm not merging this until the GitHub CI is fixed.

All jobs seem to have succeeded on [CircleCI](https://circleci.com/gh/strongly-typed/modm/tree/feature%2Fpython3).

What fix do you expect from 'GitHub CI'?

**Comment by salkinium** [comment]
> All jobs seem to have succeed on CircleCI.

No, all jobs succeeded on YOUR CircleCI instance which isn't correctly displayed here.

> What fix do you expect from 'GitHub CI'?

I expect not to have to treat your contributions as special PRs. Now I have to go and manually check if all the jobs succeeded. I know this is a bug not related to you, yet this is just more busy work for me for no reason. Why do I even have to argue about this?

**Comment by strongly-typed** [comment]
> I expect not to have to treat your contributions as special PRs. Now I have to go and manually check if all the jobs succeeded. I know this is a bug not related to you, yet this is just more busy work for me for no reason. Why do I even have to argue about this?

Keep calm ;-). Of course you don't have to argue that this is unnecessary extra work. I just learnt that the behaviour of my PR is different to other PRs. I was assuming that this was kind of (bad) design of Github/CircleCI to reuse the contributor's CI.

Do you have any clue how to change the behaviour? Can I do something about it?

**Comment by strongly-typed** [comment]
This might help:

https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

I'll work on it today.

**Comment by salkinium** [comment]
> I just learnt that the behaviour of my PR is different to other PRs. I was assuming that this was kind of (bad) design of Github/CircleCI to reuse the contributor's CI.

Well… on the upside: your PRs are ✨ truly ✨ special ✨ 🤪

**Comment by salkinium** [comment]
Just FYI: the modm-build docker is finished, so any builds are now using the latest gcc toolchain.

**Comment by salkinium** [comment]
Yay, the CI is working correctly again! 🍾 🎉 🎊

**Comment by strongly-typed** [comment]
image

Here you go, the job was now triggered on the organisation's CI 😎🥳

Need to check later if the branches of my fork are still being build without a PR.

**Comment by strongly-typed** [comment]
> Just FYI: the modm-build docker is finished, so any builds are now using the latest gcc toolchain.

Great to hear! ... and without Python2. So you should merge this asap.

**Review by salkinium — DISMISSED** [review]

**Comment by salkinium** [comment]
> So you should merge this asap.

Then you should rebase asap. 😛

**Pull request merged**
