### PR TITLE
[fix] gdb.py signal handler for linux

### LINKED ISSUE #784: Debug python script cannot handle CTRL-C on Linux
On a linux (Fedora) platform it's not possible to press CTRL-C in GDB to stop execution without GDB terminates completely. I have solved the problem by adding a signal handler to `modm_tools/gdb.py` which does nothing except catching the signal. Does anyone have the same problem, on google it's a known problem then using gdb/openocd, I will be happy to make a PR since it's a annoying feature.

Solution:
``` python
import signal

def signal_handler(sig, frame):
    pass
```
And somewhere in main activate it:
``` python
signal.signal(signal.SIGINT, signal_handler)
```

### PR DESCRIPTION
**Pull request by ghost**
CTRL-C on Linux platform breaks the GDB process and leaves the terminal in a broken state, instead of breaking the debugged program. SIGINT handler added to fix the problem.

### CODE REVIEW

**Comment by salkinium** [comment]
I've tested this and it doesn't break anything on macOS, so I'm going to merge this fix. @rleh can you test on Linux?

**Comment by rleh** [comment]
> @rleh can you test on Linux?

I'll check...

**Comment by chris-durand** [comment]
I have also tested it on Ubuntu and it didn't break anything. It is weird that I couldn't reproduce the original bug neither on Arch nor Ubuntu.

**Comment by chris-durand** [comment]
Also when I tried it with `gnome-terminal` it didn't occur, but let's merge it if it does not cause any issues for anyone else.

**Review by salkinium — APPROVED** [review]

**Review by chris-durand — APPROVED** [review]

**Pull request merged**
