### PR TITLE
[freertos] Fix clock linker error

### PR DESCRIPTION
**Pull request by chris-durand**
Now fixing both issues.

### CODE REVIEW

**Comment by chris-durand** [comment]
CI has unrelated issues:
```
ld: release/test.elf section `.text' will not fit in region `FLASH'
ld: region `FLASH' overflowed by 10488 bytes
```
Code is to big in one example ...

**Comment by rleh** [comment]
> Code is to big in one example ...

Already is fixed in #521 (2a9bb8a0f4fcd582ed89cbcc815338a99770f1ae).

**Comment by rleh** [comment]
Do we want to merge once all the other tests pass or do you want to cherry-pick the commit?

**Comment by rleh** [comment]
> once all the other tests pass

Other tests are blocked because _unittests-linux-generic_ has failed.
grafik

**Review by rleh — APPROVED** [review]

**Comment by rleh** [comment]
Ready to merge (once all tests pass) @chris-durand?

**Comment by chris-durand** [comment]
We could merge it.

**Pull request merged**
