### PR TITLE
[ext] Update submodules

### PR DESCRIPTION
**Pull request by salkinium**
Updated and compiled without issues:
- [x] STM32H5 headers v1.2.0 -> v1.3.0
- [x] STM32L4 headers  v1.12.1 -> v1.12.2
- [x] STM32F1 headers  v4.3.4 -> v4.3.5
- [x] ETL v20.38.17 -> v20.39.4
- [x] NanoPB v0.4.8 -> v0.4.9
- [x] CMSIS-DSP v1.15.0 -> v1.16.2

Updated and compiled with changes:
- [x] TinyUSB v0.16.0 -> v0.17.0
- [x] printf v6.1.0 -> v6.2.0
- [x] LVGL v8.3.11 -> v9.2.0
- [x] CMSIS-Core v5.9.0 -> v6.1.0

Tested in hardware:
- [x] TinyUSB
  - [x] DISCO-F429: MSC, CDC
  - [x] DISCO-F3: DFU
- [x] printf
- [x] LGVL
  - [x] DISCO-F469 
  - [ ] NUCLEO-L452
- [x] CMSIS-Core
- [x] CMSIS-DSP
  - [x] NUCLEO-F429
- [x] Unit Tests
  - [x] NUCLEO-F429

### CODE REVIEW

**Comment by chris-durand** [comment]
Can we add another change before merging this? printf doesn't compile on hosted from gcc 13. There is a warning about a potentially uninitialized variable that is treated as an error:

```
In function ‘apply_scaling’,
    inlined from ‘get_normalized_components’ at modm/ext/printf/printf.c:706:29,
    inlined from ‘print_exponential_number’ at modm/ext/printf/printf.c:964:5:
modm/ext/printf/printf.c:658:66: error: ‘normalization.raw_factor’ may be used uninitialized [-Werror=maybe-uninitialized]
  658 |   return normalization.multiply ? num * normalization.raw_factor : num / normalization.raw_factor;
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modm/ext/printf/printf.c: In function ‘print_exponential_number’:
modm/ext/printf/printf.c:904:25: note: ‘normalization.raw_factor’ was declared here
  904 |   struct scaling_factor normalization;
      |                         ^~~~~~~~~~~~~
```

Another function `unapply_scaling` has a workaround for it which disables the warning for one line of code. Looks like we have to duplicate that.

**Comment by chris-durand** [comment]
https://github.com/modm-ext/printf-partial/pull/1

**Comment by salkinium** [comment]
Of course! I'll get back to this PR on the weekend.

**Comment by salkinium** [comment]
@chris-durand added your patch, pls retest.

**Comment by chris-durand** [comment]
> @chris-durand added your patch, pls retest.

It works, thanks!

**Pull request merged**
