### PR TITLE
[stm32] fix adc clock source configured incorrectly on stm32g4

### PR DESCRIPTION
**Pull request by nicoBruhn**
The adc clock select was configured incorrectly for stm32g4. According to the reference manual it should be as follows:
image

### CODE REVIEW

**Comment by rleh** [comment]
Yes. Same issue I started to fix in #324.

**Review by rleh — APPROVED** [review]
Looks fine. Thanks!

Does it work on hardware @nicoBruhn?

**Comment by nicoBruhn** [comment]
I won't have access to a stm32g4 until later this week.

**Comment by rleh** [comment]
Ok, then let's wait with the merge until this has been tested on hardware.
I should also have a Nucleo-G474 lying around, but I will not find time to test it before the weekend.

**Comment by rleh** [comment]
I added an example for the Nucleo_G474RE board and tested it: It works!

**Review by rleh — APPROVED** [review]

**Comment by rleh** [comment]
Oops, I was too impatient for TravisCI and merged too early.

**Comment by salkinium** [comment]
Didn't we replace the Travis macOS runner with GH Actions? Did I forget to disable that?

**Comment by rleh** [comment]
The TravisCI job is not for macos but for linux on arm64/Aarch64, because Travis is currenttly the only CI service with arm64 VMs.

**Pull request merged**
