### PR TITLE
Add clock source for timers

### PR DESCRIPTION
**Pull request by dergraaf**
The blue and black pill board files are missing the clock sources for timers.

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Thanks!

**Comment by salkinium** [comment]
I‘m working on parsing the Clocktree data in modm-devices, to at least generate this clock domain <–> peripheral mapping automatically. But it‘s still pretty complicated 🤔

**Comment by dergraaf** [comment]
I can imagine that. At the moment the clock configuration is the most annoying thing if you want to start a new project from scratch without copying an exisiting project. Just too many options and things to consider.

**Comment by dergraaf** [comment]
Btw. how do you restart the CI tests? The failure seems to be mainly related to the Circle-CI docker-hub problems yesterday.

**Comment by salkinium** [comment]
> Btw. how do you restart the CI tests?

Login to CircleCI with GitHub and it automatically gives you access to restart modm jobs, unless more magic is involved 🤷‍♂️.

**Review by salkinium — DISMISSED** [review]

**Pull request merged**
