### PR TITLE
Fix unintended paragraph in documentation.

### PR DESCRIPTION
**Pull request by dhebbeker**
Apparently starting the new line with `<!--` in Markdown introduces new paragraph? :shrug:

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Thanks! This depends on the Markdown parser, for example the homepage does not have this issue…

**Comment by salkinium** [comment]
Oh wait, actually the homepage does have this issue! 😱 
Screenshot 2021-01-05 at 14 59 29

**Comment by salkinium** [comment]
It's all over the place…
Screenshot 2021-01-05 at 15 00 07

**Comment by salkinium** [comment]
I also fixed the `33 contributers` issue, will merge as soon as the CI passes.

**Review by rleh — APPROVED** [review]

**Comment by dhebbeker** [comment]
> Oh wait, actually the homepage does have this issue! :scream:

That is actually how I stumbled upon it :smile:

**Pull request merged**
