### PR TITLE
Ili9341 support (SPI only).

### PR DESCRIPTION
**Pull request by mikewolfram**
First version of ILI9341 support. Currently SPI only. For comparison with version of @ASMfreaK.

### CODE REVIEW

**Comment by asmfreak** [comment]
I'd like to work on this implementation to add parallel bus interface, but I'm not sure about the copyright notice on the files.

**Comment by mikewolfram** [comment]
> I'd like to work on this implementation to add parallel bus interface, but I'm not sure about the copyright notice on the files.

Sorry, happens to me all the time. Fixed the copyright.

**Comment by mikewolfram** [comment]
BTW, I have also code for Ili9486, which is basically the same like the Ili9341 (few registers different only). That code uses 16 bits parallel interface. If you want I can open another PR with that code.

For the parallel interface I was thinking to implement DMA support as well.

**Comment by salkinium** [comment]
This PR has been merged into #437 which also adds a parallel interface to the driver. Thanks!

**Pull request closed without merging**
