### PR TITLE
Feature/nucleo f446

### PR DESCRIPTION
**Pull request by se-bi**
Do you want it besides rebased also squashed into one commit?

### CODE REVIEW

**Comment by salkinium** [comment]
Something like 3 commits would be nice:

1. Add board
2. Add example
3. Add test

**Comment by salkinium** [comment]
CI will start for the next push, I experimented with something that didn't work in the config.

**Comment by se-bi** [comment]
Finally,
script checking the doc is also happy

**Review by salkinium — DISMISSED** [review]
Great, thanks!

**Comment by se-bi** [comment]
Now, that CI verified,
might not be integrated in the CI run itself :see_no_evil:

**Comment by salkinium** [comment]
~~Also add the unittest run.~~ kinda redundant.

**Pull request merged**
