### PR TITLE
Add WaitForInterrupt to resumeables

### PR DESCRIPTION
**Pull request by henrikssn**
More context in #432

### CODE REVIEW

**Comment by salkinium** [comment]
Is this more of a Draft, ie. do you want to add some examples/scheduler code or do you want this merged as is?

**Comment by henrikssn** [comment]
Sorry, definitely needs examples/docs, I was just looking for some initial feedback to learn how this matched our discussion earlier.

One thing that came to my mind is that there does not seem to be a pattern for running resumeables concurrently at the moment (which doesn't make sense to me, then we could just do things blocking). What am I missing?

**Comment by salkinium** [comment]
`RF_CALL_BLOCKING` is just a convenience/debug macro, without forward progress guarantee (it doesn't update anything else after all). Resumables are only scoped around (nested) functions, the application should consists out of several concurrent Protothreads that call resumables via `PT_CALL`:

```c++
bool MyThread::update()
{
    PT_BEGIN();
    while(true)
    {
        PT_CALL(resumable());
        PT_YIELD(); // or wait until timer, or on some condition
    }
    PT_END();
}
```

You would then run multiple protothread together by calling their `update()` function in the main loop. That's the bespoke way to run resumables concurrently, and it mirrors the use of pre-emptive threading, where you cannot call two "normal" functions at the same time either.

This is mostly a semantical difference, the protothread implementation is slightly different and I had to keep it for backwards compatibility. You can implement the same with Resumables just slightly more annoying. With C++20 there would probably not be a difference between Protothreads and Resumables anymore, this is currently just historical baggage.

If you mean, running two resumables in parallel, via some "join" operation this is possible with non-nested resumables, which have a `obj.join({1,2,3,4})` function, but it's not very user-friendly. The RF_CALL macro magic limits the possiblities here, this would be better with C++ coroutines objects, with their proper call API. In general I'm not happy exposing such a low-level API, I've been bitten a lot by raw threads and really enjoy using abstractions like worker thread pools or event loops, etc…, so I didn't advertise such operations on resumables in the docs/examples.

**Comment by salkinium** [comment]
So in this context, you would implement the call to `WFI()` in `PT_CALL` macro, right? And make the leaf optimization part of the Protothread class implementation? The Resumables are just communicating their state up, the protothread has to interpret it.

So the implicit scheduler consists of:
 
1. `main() { while(1) {} }` loop calls `Protothread.update()`
2. Protothread calls resumable via `PT_CALL(resumable)` (it can also spawn other protothreads via `PT_SPAWN()`, these were the precursor to resumbales, so their never used anymore.).
3. Resumable calls (nested) resumable via `RF_CALL(resumable)`.

**Comment by henrikssn** [comment]
Hmm, I still don't see how protothreads run multiple things at once (they are just resumables with different name, right?)

If I understand correctly, `PT_SPAWN` is waiting on completion of the child thread which does not allow for concurrency.

Take this example:

```c++
bool ChildOne::update()
{
    PT_BEGIN();
    while(true)
    {
        PT_WAIT_UNTIL(timer.execute());
        LedOne::toggle();
    }
    PT_END();
private:
  PeriodicTimer timer(100ms);
}

bool ChildTwo::update()
{
    PT_BEGIN();
    while(true)
    {
        PT_WAIT_UNTIL(timer.execute());
        LedTwo::toggle();
    }
    PT_END();
private:
  PeriodicTimer timer(200ms);
}
```

and the main loop implemented as `main() { while(1) { mainThread.update() } }`.

How do you implement the mainThread so that LedOne toggles every 100ms and LedTwo every 200ms?

**Comment by salkinium** [comment]
There is no mainThread, you have to call every thread's update method manually. modm does not schedule anything for you at all. *You* are the scheduler!

You can group your threads manually into another thread, and "centralize" the call to update() of your "child" threads, but you still have to call their update() functions *somewhere*.

```c++
Thread1 thread1;
Thread2 thread2;
modm::ShortPeriodicTimer tmr(1s);

bool
MoreThreads::update()
{
    // Call before PT_BEGIN()
    thread3.update();
    thread4.update();

    PT_BEGIN();
    while(1)
    {
        PT_YIELD();
    }
    PT_END();
}

MoreThreads moreThreads;

int main()
{
    Board::initialize();

    while(1)
    {
        thread1.update();
        thread2.update();
        moreThreads.update();

        // "inline" Protothread
        if (tmr.execute()) LedThree::toggle();
    }
    return 0;
}
```

**Comment by henrikssn** [comment]
Thanks, that makes it clear.

What is missing then is some way to check the result type of all the "top level threads" and either loop around or issue WFI instruction. Sure, you can already do something like

```
    while(1)
    {
        sleep = true;
        if(resumeable1.resume().getState() == modm::rf::WaitForInterrupt) sleep &= true;
        if(resumeable2.resume().getState() == modm::rf::WaitForInterrupt) sleep &= true;
        if(resumeable3.resume().getState() == modm::rf::WaitForInterrupt) sleep &= true;
        // ...
        if (sleep) WFI();
    }
```

But maybe we want to prettify this? The boring part is that it would need to be implemented twice if we also want it for protothreads...

**Comment by salkinium** [comment]
> But maybe we want to prettify this?

Yes, that's what I meant with adding a separate module `:processing:sleep`, that centralizes the configuration of this.

**Comment by salkinium** [comment]
I'm closing this in favor of fibers and also in the long term the removal of protothread/resumable functions (in favor of fibers).

**Pull request closed without merging**
