### PR TITLE
[stm32] Add support for advanced timer channels 5,6 and TRGO2

### PR DESCRIPTION
**Pull request by chris-durand**
This adds advanced control timer channels 5 and 6 and trigger out 2 for all STM32 supporting these functions.

The STM32 timer API really needs refactoring but I don't have time to do it right now …

### CODE REVIEW

**Comment by salkinium** [comment]
> The STM32 timer API really needs refactoring but I don't have time to do it right now …

I know that feel… 😞

**Review by salkinium — APPROVED** [review]
I don't have any objections, but I'm waiting for @rleh to have a quick look, since he knows the API better than me.

**Review by rleh — APPROVED** [review]
Nice 👍🏽

**Comment by rleh** [comment]
@salkinium Was your push just a rebase or did you change something?

**Comment by salkinium** [comment]
just a rebase, sorry

**Pull request merged**
